version: 0.2

phases:
    install:
          runtime-versions:
                  java: corretto8
                    build:
                          commands:
                                  - echo Build started on `date`
                                          - aws s3 cp "s3://application-54321/index.html" "index.html" --recursive
                                                  - echo Build completed on `date`
                                                      post_build:
                                                            commands:
                                                                    - echo Build completed on `date`
                                                            artifacts:
                                                                files:
                                                                        - "**/*"
